/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as FurtherReadingRouteImport } from './routes/further-reading'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WhyWeExistRouteImport } from './routes/why-we-exist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const FurtherReadingRoute = FurtherReadingRouteImport.update({
  id: '/further-reading',
  path: '/further-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyWeExistRoute = WhyWeExistRouteImport.update({
  id: '/why-we-exist',
  path: '/why-we-exist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/further-reading': typeof FurtherReadingRoute
  '/shop': typeof ShopRoute
  '/why-we-exist': typeof WhyWeExistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/further-reading': typeof FurtherReadingRoute
  '/shop': typeof ShopRoute
  '/why-we-exist': typeof WhyWeExistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/further-reading': typeof FurtherReadingRoute
  '/shop': typeof ShopRoute
  '/why-we-exist': typeof WhyWeExistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/further-reading' | '/shop' | '/why-we-exist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/further-reading' | '/shop' | '/why-we-exist'
  id:
    '__root__' | '/' | '/blog' | '/further-reading' | '/shop' | '/why-we-exist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  FurtherReadingRoute: typeof FurtherReadingRoute
  ShopRoute: typeof ShopRoute
  WhyWeExistRoute: typeof WhyWeExistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/further-reading': {
      id: '/further-reading'
      path: '/further-reading'
      fullPath: '/further-reading'
      preLoaderRoute: typeof FurtherReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-we-exist': {
      id: '/why-we-exist'
      path: '/why-we-exist'
      fullPath: '/why-we-exist'
      preLoaderRoute: typeof WhyWeExistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  FurtherReadingRoute: FurtherReadingRoute,
  ShopRoute: ShopRoute,
  WhyWeExistRoute: WhyWeExistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
